name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  header:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          template: classic
          filename: assets/metrics/header.svg
          base: header
          config_timezone:  ${{ secrets.USER_TIMEZONE }}
  
  achievements:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          template: classic
          filename: assets/metrics/achievements.svg
          base: achievements
          config_timezone:  ${{ secrets.USER_TIMEZONE }}
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

  isocalendar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          commiter_token: ${{ secrets.GITHUB_TOKEN }}
          # Options
          template: classic
          filename: assets/metrics/isocalendar.svg
          base: ""
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

  repositories:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          commiter_token: ${{ secrets.GITHUB_TOKEN }}
          # Options
          user: zailic
          template: classic
          filename: assets/metrics/repositories.svg
          base: repositories
          config_timezone: ${{ secrets.USER_TIMEZONE }}

  actitivity_community:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          commiter_token: ${{ secrets.GITHUB_TOKEN }}
          # Options
          user: zailic
          template: classic
          filename: assets/metrics/act_comm.svg
          base: activity, community
          config_timezone: ${{ secrets.USER_TIMEZONE }}

  habits:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          commiter_token: ${{ secrets.GITHUB_TOKEN }}
          # Options
          user: zailic
          template: classic
          filename: assets/metrics/habits.svg
          base: ""
          plugin_habits: yes
          plugin_habits_from: 200       
          plugin_habits_days: 60        
          plugin_habits_charts: yes     
          plugin_habits_trim: yes       
          config_timezone: ${{ secrets.USER_TIMEZONE }}

  lines:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          commiter_token: ${{ secrets.GITHUB_TOKEN }}
          # Options
          user: zailic
          template: classic
          filename: assets/metrics/lines.svg
          base: "repositories"
          config_timezone: ${{ secrets.USER_TIMEZONE }}
