name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        name: header
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          template: classic
          filename: assets/metrics/header.svg
          base: header
          config_timezone:  ${{ secrets.USER_TIMEZONE }}
      - uses: lowlighter/metrics@latest
        name: achievements
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          template: classic
          filename: assets/metrics/achievements.svg
          base: achievements
          config_timezone:  ${{ secrets.USER_TIMEZONE }}
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
      - uses: lowlighter/metrics@latest
        name: isocalendar
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          # Options
          template: classic
          filename: assets/metrics/isocalendar.svg
          base: ""
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
      - uses: lowlighter/metrics@latest
        name: repositories
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          # Options
          user: zailic
          template: classic
          filename: assets/metrics/repositories.svg
          base: repositories
          config_timezone: ${{ secrets.USER_TIMEZONE }}
      - uses: lowlighter/metrics@latest
        name: "activity & community"
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          # Options
          user: zailic
          template: classic
          filename: assets/metrics/act_comm.svg
          base: activity, community
          config_timezone: ${{ secrets.USER_TIMEZONE }}
      - uses: lowlighter/metrics@latest
        name: "habits"
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          # Options
          user: zailic
          template: classic
          filename: assets/metrics/habits.svg
          base: ""
          plugin_habits: yes
          plugin_habits_from: 200       
          plugin_habits_days: 60        
          plugin_habits_charts: yes     
          plugin_habits_trim: yes       
          config_timezone: ${{ secrets.USER_TIMEZONE }}
      - uses: lowlighter/metrics@latest
        name: languages
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          # Options
          user: zailic
          base: ""
          template: classic
          filename: assets/metrics/followup_lang.svg
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: 8
          plugin_languages_analysis_timeout: 15
          plugin_followup: yes
          config_timezone: ${{ secrets.USER_TIMEZONE }}